### ISSUE TITLE
This ruined 5 months worth of my life.

### ISSUE THREAD

**Issue by alexprice91** [colinhemphill/git-gut#1]
What the heck? I can't find my code I have been working on for the last 5 months!

**Comment by colinhemphill** [comment]
😝

**Comment by colinhemphill** [comment]
Should've read the disclaimer. 😉
> I am not responsible for any accidental damage or loss of Git repository due to the usage of this command line tool.

**Comment by cinder92** [comment]
AJAJAJJAJAJAJAJAJAJAJAJAJAJA love this repository <3
