### ISSUE TITLE
typing 'gut status' should close terminal

### ISSUE THREAD

**Issue by blaynem** [colinhemphill/git-gut#2]
I think this would be an incredible feature.

**Comment by cinder92** [comment]
HAHAHAHAHAHHAHAHAHAHAHAHHAAH <3 comments

**Comment by felipemfp** [comment]
What about `git checkout -- *`?

**Comment by colinhemphill** [comment]
Oddly enough, someone (@itsananderson) already has an NPM package called `gut-status`. His package is far less destructive than mine, but was created before I started `git-gut`. I'm glad I'm not the only one who thought that mistyping `git` should do something funny, but my head went to a much darker place. hahaha 😈

https://www.npmjs.com/package/gut-status
